"""Constants for bookstack_sync."""

from __future__ import annotations

from logging import Logger, getLogger

LOGGER: Logger = getLogger(__package__)

DOMAIN = "bookstack_sync"

CONF_BASE_URL = "base_url"
CONF_TOKEN_ID = "token_id"  # noqa: S105 - config-entry field name, not a secret
CONF_TOKEN_SECRET = "token_secret"  # noqa: S105 - field name, not a secret
CONF_BOOK_ID = "book_id"
CONF_SYNC_INTERVAL = "sync_interval"
CONF_VERIFY_SSL = "verify_ssl"
CONF_EXCLUDED_AREAS = "excluded_areas"
CONF_OUTPUT_LANGUAGE = "output_language"

DEFAULT_VERIFY_SSL = True
# "auto" follows hass.config.language; explicit codes ("de", "en") override it
OUTPUT_LANGUAGE_AUTO = "auto"
DEFAULT_OUTPUT_LANGUAGE = OUTPUT_LANGUAGE_AUTO

INTERVAL_HOURLY = "hourly"
INTERVAL_DAILY = "daily"
INTERVAL_MANUAL = "manual"

DEFAULT_INTERVAL = INTERVAL_DAILY

SYNC_INTERVALS = {
    INTERVAL_HOURLY: 60 * 60,
    INTERVAL_DAILY: 24 * 60 * 60,
    INTERVAL_MANUAL: 0,
}

AUTO_BEGIN_MARKER = "<!-- BEGIN AUTO-GENERATED -->"
AUTO_END_MARKER = "<!-- END AUTO-GENERATED -->"
MANUAL_BEGIN_MARKER = "<!-- BEGIN MANUAL -->"
MANUAL_END_MARKER = "<!-- END MANUAL -->"

STORAGE_VERSION = 1
STORAGE_KEY_FMT = "bookstack_sync.{entry_id}.mapping"

PAGE_KIND_OVERVIEW = "overview"
PAGE_KIND_AREA = "area"
PAGE_KIND_DEVICE = "device"
PAGE_KIND_AUTOMATIONS = "automations"
PAGE_KIND_SCRIPTS = "scripts"
PAGE_KIND_SCENES = "scenes"
PAGE_KIND_INTEGRATIONS = "integrations"
PAGE_KIND_ADDONS = "addons"

# Chapters group the many area/device pages so the book stays readable.
# Titles + descriptions come from `_strings.py` so they follow the user's
# selected output language.
CHAPTER_KEY_AREAS = "areas"
CHAPTER_KEY_DEVICES = "devices"

# BookStack page tags applied by the integration so users can filter
# the book by tag in BookStack's UI ("Filter by tag" → bookstack_sync ...).
TAG_NAME = "bookstack_sync"
TAG_VALUE_MANAGED = "managed"
TAG_VALUE_ORPHANED = "orphaned"

SERVICE_RUN_NOW = "run_now"
SERVICE_PREVIEW = "preview"

ATTRIBUTION = "Auto-generated by Home Assistant via ha-bookstack-sync"
