"""
Markdown back-export from BookStack to a folder of plain files (issue #61, A4).

Reads every page that ha-bookstack-sync manages (tag ``bookstack_sync = managed``
or ``= orphaned``), splits AUTO and MANUAL blocks, builds YAML frontmatter, and
writes one Markdown file per page idempotently. The output folder becomes a
universal RAG input source — LangChain, LlamaIndex, Open WebUI etc. all consume
this format natively.

Off-by-default: callers (the service handler in ``services.py`` and the
auto-trigger in ``coordinator.py``) gate on the ``export_enabled`` option. This
module itself runs whenever called — the gate lives one layer up so the user's
opt-in is enforced at every entry point.
"""

from __future__ import annotations

import contextlib
import hashlib
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any

from .api import BookStackApiError
from .const import (
    DEFAULT_EXPORT_SUBDIR,
    LOGGER,
    TAG_NAME,
    TAG_VALUE_MANAGED,
    TAG_VALUE_ORPHANED,
)
from .export_store import BookStackSyncExportStore, ExportEntry
from .frontmatter import build as build_frontmatter
from .frontmatter import to_yaml
from .merge import split_blocks
from .slug import make_unique_slug, slugify

if TYPE_CHECKING:
    from collections.abc import Callable

    from homeassistant.core import HomeAssistant

    from .api import BookStackApiClient
    from .data import BookStackSyncConfigEntry
    from .store import BookStackSyncStore


_ALLOWED_TAG_VALUES = frozenset({TAG_VALUE_MANAGED, TAG_VALUE_ORPHANED})


@dataclass(frozen=True)
class ExportResult:
    """Counts + path for one export run."""

    written: int
    unchanged: int
    deleted_old: int
    errors: int
    output_path: str


def default_output_path(hass: HomeAssistant) -> Path:
    """Return ``<config>/bookstack_export``."""
    return Path(hass.config.path(DEFAULT_EXPORT_SUBDIR))


def _resolve_output_path(
    hass: HomeAssistant,
    override: str | Path | None,
) -> Path:
    if override is None:
        return default_output_path(hass)
    return Path(override)


def _is_managed_or_orphaned(page: dict[str, Any]) -> bool:
    """Accept pages tagged by ha-bookstack-sync; ignore foreign wiki pages."""
    for tag in page.get("tags") or []:
        if tag.get("name") == TAG_NAME and tag.get("value") in _ALLOWED_TAG_VALUES:
            return True
    return False


def _chapter_slug(chapter_id: int | None, chapter_lookup: dict[int, str]) -> str:
    """Return the folder slug for a page (root for chapterless pages)."""
    if chapter_id is None:
        return ""
    name = chapter_lookup.get(chapter_id)
    if not name:
        return f"chapter-{chapter_id}"
    return slugify(name)


def _atomic_write(path: Path, content: str) -> None:
    """Write to ``<path>.tmp`` then rename — never leaves a half-written file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(path)


def _delete_if_exists(path: Path) -> None:
    """Delete a file if it's there. Empty parent directories are pruned."""
    if not path.exists():
        return
    path.unlink()
    # Directory not empty or doesn't exist — leave it alone.
    with contextlib.suppress(OSError):
        path.parent.rmdir()


def _render_index(entries: dict[str, dict[str, Any]], output_path: Path) -> str:
    """Build the ``_index.md`` content listing all exports grouped by folder."""
    by_folder: dict[str, list[tuple[str, str]]] = {}
    for entry in entries.values():
        folder = entry["filename"].rpartition("/")[0] or "(root)"
        title = entry["title"]
        rel = entry["filename"]
        by_folder.setdefault(folder, []).append((title, rel))

    lines = [
        "# BookStack Sync — Markdown Export",
        "",
        "Auto-generated by ha-bookstack-sync. Do not edit by hand — every export "
        "regenerates this file.",
        "",
        f"Output path: `{output_path}`",
        "",
    ]
    for folder in sorted(by_folder):
        lines.append(f"## {folder}")
        lines.append("")
        for title, rel in sorted(by_folder[folder]):
            lines.append(f"- [{title}]({rel})")
        lines.append("")
    return "\n".join(lines)


async def export(  # noqa: PLR0912, PLR0915 — single linear orchestration is clearer than splitting
    hass: HomeAssistant,
    entry: BookStackSyncConfigEntry,
    *,
    dry_run: bool = False,
    output_path: str | Path | None = None,
    progress_callback: Callable[[int, int], None] | None = None,
) -> ExportResult:
    """
    Run one export pass.

    Idempotent: each page's content (frontmatter + body) is SHA-256-hashed and
    only re-written when the hash changes or the target filename changes.
    Renames cause the old file to be deleted; orphaned pages stay at their
    pre-tombstone filename so external indexers keep working.

    Returns counts and the resolved output path. ``dry_run=True`` performs all
    reads and computes the diff but writes nothing — useful for the
    ``preview``-style smoke test.
    """
    runtime = entry.runtime_data
    client: BookStackApiClient = runtime.client
    sync_store: BookStackSyncStore = runtime.store
    export_store: BookStackSyncExportStore = runtime.export_store

    target_root = _resolve_output_path(hass, output_path)
    LOGGER.info(
        "BookStack export starting (dry_run=%s, output=%s)",
        dry_run,
        target_root,
    )

    written = unchanged = deleted_old = errors = 0
    rendered: dict[str, dict[str, Any]] = {}  # mapping_key → {filename, title}
    taken_per_folder: dict[str, set[str]] = {}

    # Resolve chapter id → name once so frontmatter has readable labels.
    chapter_lookup: dict[int, str] = {}
    book_id = int(
        (entry.options or entry.data).get("book_id") or entry.data["book_id"],
    )
    try:
        chapters = await client.list_chapters(book_id)
    except BookStackApiError as err:
        LOGGER.warning("Could not list chapters for export: %s", err)
        chapters = []
    for chapter in chapters:
        chapter_lookup[int(chapter["id"])] = str(chapter.get("name", ""))

    now_iso = datetime.now(tz=UTC).isoformat(timespec="seconds")

    # First pass: figure out target filenames so we can detect collisions
    # deterministically before we write anything.
    plan: list[tuple[str, dict[str, Any], Path, str]] = []
    for mapping_key, mapping_entry in sync_store.all().items():
        try:
            page = await client.get_page(mapping_entry.page_id)
        except BookStackApiError as err:
            LOGGER.warning(
                "Skipping export for %s (page %d): %s",
                mapping_key,
                mapping_entry.page_id,
                err,
            )
            errors += 1
            continue
        if not _is_managed_or_orphaned(page):
            LOGGER.debug(
                "Page %d is not tagged %s=%s/%s — skipping",
                mapping_entry.page_id,
                TAG_NAME,
                TAG_VALUE_MANAGED,
                TAG_VALUE_ORPHANED,
            )
            continue
        chapter_id_raw = page.get("chapter_id")
        chapter_id = int(chapter_id_raw) if chapter_id_raw else None
        folder = _chapter_slug(chapter_id, chapter_lookup)
        title = str(page.get("name", "untitled"))
        base_slug = slugify(title)
        taken = taken_per_folder.setdefault(folder, set())
        # Reuse the previous slug for stable filenames if the title has not
        # changed enough to alter slugify's output. Otherwise pick a fresh
        # collision-free slug for this folder.
        prev = export_store.get(mapping_key)
        if prev and prev.filename.startswith(f"{folder}/" if folder else ""):
            prev_slug = Path(prev.filename).stem
            slug_now = slugify(title)
            if slug_now in (prev_slug, prev_slug.rsplit("-", 1)[0]):
                final_slug = prev_slug
            else:
                final_slug = make_unique_slug(base_slug, taken)
        else:
            final_slug = make_unique_slug(base_slug, taken)
        taken.add(final_slug)
        rel = f"{folder}/{final_slug}.md" if folder else f"{final_slug}.md"
        plan.append((mapping_key, page, target_root / rel, rel))

    # Second pass: render + diff + write.
    # v0.14.7: emit a (0, total) seed tick so the diagnostic sensor jumps
    # from "Export läuft" straight to "Export läuft 0/N" before any I/O —
    # avoids a brief stretch where the user sees the bare ``export`` enum.
    total_to_process = len(plan)

    def _tick(step: int) -> None:
        if progress_callback is not None:
            progress_callback(step, total_to_process)

    _tick(0)
    for processed, (mapping_key, page, target_path, rel) in enumerate(plan, start=1):
        _tick(processed)
        mapping_entry = sync_store.get(mapping_key)
        if mapping_entry is None:
            continue
        auto, manual = split_blocks(str(page.get("markdown", "")))
        body = (auto.strip() + "\n\n---\n\n" + manual.strip()).strip() + "\n"
        fm = build_frontmatter(
            mapping_key=mapping_key,
            bookstack_page=page,
            book_id=book_id,
            chapter_lookup=chapter_lookup,
            tombstoned=mapping_entry.tombstoned_at is not None,
            last_synced=mapping_entry.last_seen or "",
        )
        # Hash the body+frontmatter (without content_hash field) so the hash
        # is stable across runs that don't change anything.
        partial_yaml = to_yaml(fm, content_hash="")
        partial_full = f"---\n{partial_yaml}---\n\n{body}"
        content_hash = hashlib.sha256(partial_full.encode("utf-8")).hexdigest()
        full = f"---\n{to_yaml(fm, content_hash)}---\n\n{body}"

        prev = export_store.get(mapping_key)
        if (
            prev
            and prev.content_hash == content_hash
            and prev.filename == rel
            and target_path.exists()
        ):
            unchanged += 1
            rendered[mapping_key] = {"filename": rel, "title": fm.title}
            continue

        if prev and prev.filename != rel:
            old_path = target_root / prev.filename
            if not dry_run:
                _delete_if_exists(old_path)
            deleted_old += 1

        if not dry_run:
            try:
                _atomic_write(target_path, full)
            except OSError as err:
                LOGGER.warning("Failed to write %s: %s", target_path, err)
                errors += 1
                continue
            export_store.set(
                mapping_key,
                ExportEntry(
                    page_id=int(page["id"]),
                    filename=rel,
                    content_hash=content_hash,
                    last_exported=now_iso,
                ),
            )
        written += 1
        rendered[mapping_key] = {"filename": rel, "title": fm.title}

    # Drop ledger rows for pages that no longer come back from the sync store
    # (e.g. the user removed an integration). We don't delete the file —
    # tombstoned pages legitimately disappear from the sync mapping eventually.
    stale = set(export_store.all()) - set(rendered)
    for key in stale:
        export_store.remove(key)

    # Always regenerate _index.md so it reflects the current state.
    if not dry_run and rendered:
        index_content = _render_index(rendered, target_root)
        index_path = target_root / "_index.md"
        try:
            _atomic_write(index_path, index_content)
        except OSError as err:
            LOGGER.warning("Failed to write _index.md: %s", err)
            errors += 1

    if not dry_run:
        await export_store.async_save()

    result = ExportResult(
        written=written,
        unchanged=unchanged,
        deleted_old=deleted_old,
        errors=errors,
        output_path=str(target_root),
    )
    LOGGER.info(
        "BookStack export done: %d written, %d unchanged, %d deleted, %d errors",
        result.written,
        result.unchanged,
        result.deleted_old,
        result.errors,
    )
    return result
